import { Telescope, Sparkles, Globe2, Binary, Milestone } from "lucide-react";

const gradient = "bg-gradient-to-r from-purple-400 via-fuchsia-400 to-blue-400 text-transparent bg-clip-text";

export function DifferenceSection() {
  return (
    <section className="py-24 px-4 max-w-6xl mx-auto text-center">
      <h2 className="text-3xl md:text-4xl font-bold mb-16">
        What Makes <span className={gradient}>Z13 Different?</span>
      </h2>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
        {/* Accurate Astronomy */}
        <div className="block w-full p-6 rounded-xl border border-gray-700/40 bg-white/5 backdrop-blur-sm hover:shadow-neon transition duration-500 text-left">
          <Telescope className="text-neon-cyan mb-4" size={32} />
          <h3 className="text-lg md:text-xl font-bold mb-2">Astronomy-Accurate</h3>
          <p className="text-gray-300 text-sm md:text-base">
            Planetary positions pulled from NASA JPL ephemeris - reflecting
            where the sky truly is, not where it was 2,000 years ago.
          </p>
        </div>

        {/* True Constellation Sizes */}
        <div className="block w-full p-6 rounded-xl border border-gray-700/40 bg-white/5 backdrop-blur-sm hover:shadow-neon-magenta transition duration-500 text-left">
          <Globe2 className="text-neon-purple mb-4" size={32} />
          <h3 className="text-lg md:text-xl font-bold mb-2">Real Constellations</h3>
          <p className="text-gray-300 text-sm md:text-base">
            Z13 uses the actual constellation boundaries defined by the IAU -
            including Ophiuchus - with true sizes and positions.
          </p>
        </div>

        {/* Modern & Inclusive */}
        <div className="block w-full p-6 rounded-xl border border-gray-700/40 bg-white/5 backdrop-blur-sm hover:shadow-neon transition duration-500 text-left">
          <Sparkles className="text-neon-yellow mb-4" size={32} />
          <h3 className="text-lg md:text-xl font-bold mb-2">Modern & Inclusive</h3>
          <p className="text-gray-300 text-sm md:text-base">
            Z13 embraces both Tropical and True-Sky astrology, letting you explore
            multiple perspectives without choosing sides.
          </p>
        </div>

        {/* Data-Driven */}
        <div className="block w-full p-6 rounded-xl border border-gray-700/40 bg-white/5 backdrop-blur-sm hover:shadow-neon-magenta transition duration-500 text-left">
          <Binary className="text-neon-cyan mb-4" size={32} />
          <h3 className="text-lg md:text-xl font-bold mb-2">Data-Driven</h3>
          <p className="text-gray-300 text-sm md:text-base">
            Every calculation is generated by a modern ephemeris engine -
            accurate, reliable, and built for the 21st century.
          </p>
        </div>

        {/* 13 Signs */}
        <div className="block w-full p-6 rounded-xl border border-gray-700/40 bg-white/5 backdrop-blur-sm hover:shadow-neon transition duration-500 text-left">
          <Milestone className="text-neon-purple mb-4" size={32} />
          <h3 className="text-lg md:text-xl font-bold mb-2">Thirteen Signs</h3>
          <p className="text-gray-300 text-sm md:text-base">
            Beyond Pisces and Aries - Z13 includes the astronomical 13th sign,
            Ophiuchus, restoring the sky's full story.
          </p>
        </div>

        {/* Flexible & Exploratory */}
        <div className="block w-full p-6 rounded-xl border border-gray-700/40 bg-white/5 backdrop-blur-sm hover:shadow-neon-magenta transition duration-500 text-left">
          <Sparkles className="text-neon-yellow mb-4" size={32} />
          <h3 className="text-lg md:text-xl font-bold mb-2">Built for Exploration</h3>
          <p className="text-gray-300 text-sm md:text-base">
            Z13 is designed to help you explore your chart from every angle -
            symbolic, astronomical, or intuitive.
          </p>
        </div>
      </div>
    </section>
  );
}